# Generated by Django 5.2.11 on 2026-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
