# Generated by Django 5.2.11 on 2026-03-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_as_multiple', to='exams.option'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended')], default='single_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_single', to='exams.option'),
        ),
    ]
