# Generated by Django 5.2.11 on 2026-03-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_attemptanswer_selected_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
