# Generated by Django 5.2.11 on 2026-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_attemptanswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_timed',
            field=models.BooleanField(default=True),
        ),
    ]
